apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-runner-env
data:
  DRONE_RPC_HOST: drone.rappet.xyz
  DRONE_RPC_PROTO: https
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: drone
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  labels:
    app.kubernetes.io/name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-runner
    spec:
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          valueFrom:
            configMapKeyRef:
              name: drone-runner-env
              key: DRONE_RPC_HOST
        - name: DRONE_RPC_PROTO
          valueFrom:
            configMapKeyRef:
              name: drone-runner-env
              key: DRONE_RPC_PROTO
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secret
              key: DRONE_RPC_SECRET
