apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  selector:
    app: gitea
  ports:
    - protocol: TCP
      name: http
      port: 3000
    - protocol: TCP
      name: ssh
      port: 22
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-env
data:
  USER_UID: "1000"
  USER_GID: "1000"
  DB_TYPE: postgres
  DB_HOST: postgres:5432
  DB_USER: gitea
  DB_PASSWD: gitea
  ROOT_URL: https://git.rappet.xyz/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 22
          volumeMounts:
            - mountPath: /data
              name: data
          envFrom:
            - configMapRef:
                name: gitea-env
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitea-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Things gitea does not like: many requests
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "30"
spec:
  rules:
    - host: git.rappet.xyz
      http:
        paths:
          - backend:
              serviceName: gitea
              servicePort: 3000
  tls:
    - hosts:
        - git.rappet.xyz
      secretName: gitea-ingress-cert
