apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - namespace.yaml
  - gitea.yaml
  - postgres.yaml

configMapGenerator:
  - name: gitea-config
    files:
      - config/app.ini
