apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=fluxcd,ingress,cert-manager,grafana,minio,gitea,drone,foo-testpage,blog
            - --git-user=rappet
            - --git-email=raphael.r.peters@gmail.com
            - --git-url=git@github.com:rappet/kube-config
            - --sync-garbage-collection
