apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lounge

resources:
  - namespace.yaml
  - lounge.yaml

configMapGenerator:
  - name: lounge-config
    files:
      - config/config.js
