apiVersion: v1
kind: Service
metadata:
  name: lounge-http
spec:
  selector:
    app: lounge
  ports:
    - name: http
      protocol: TCP
      port: 9000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lounge-data
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lounge
spec:
  selector:
    matchLabels:
      app: lounge
  template:
    metadata:
      labels:
        app: lounge
    spec:
      containers:
        - name: lounge
          image: thelounge/thelounge:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/opt/thelounge
              name: data
            - mountPath: /var/opt/thelounge/config.js
              name: config
              subPath: config.js
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lounge-data
        - name: config
          configMap:
            name: lounge-config
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitea-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: lounge.rappet.xyz
      http:
        paths:
          - backend:
              serviceName: lounge-http
              servicePort: 9000
  tls:
    - hosts:
        - lounge.rappet.xyz
      secretName: lounge-ingress-cert
