apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: rappet/rappetxyz:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gitea-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: rappet.xyz
      http:
        paths:
          - backend:
              serviceName: blog
              servicePort: 80
    - host: www.rappet.xyz
      http:
        paths:
          - backend:
              serviceName: blog
              servicePort: 80
    - host: rappet.de
      http:
        paths:
          - backend:
              serviceName: blog
              servicePort: 80
    - host: www.rappet.de
      http:
        paths:
          - backend:
              serviceName: blog
              servicePort: 80
  tls:
    - hosts:
        - rappet.xyz
        - www.rappet.xyz
        - rappet.de
        - www.rappet.de
      secretName: blog-ingress-cert
